# Generated by Django 2.2.7 on 2019-11-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('reg_no', models.CharField(max_length=200, null=True)),
                ('telephone_number', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('cohort', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(max_length=200, null=True)),
                ('reg_no', models.CharField(max_length=200, null=True)),
                ('no_of_students', models.CharField(max_length=200, null=True)),
                ('courses_enrolled', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactus_id', models.IntegerField(null=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('reg_no', models.CharField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('response', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(max_length=200, null=True)),
                ('course_code', models.CharField(max_length=200, null=True)),
                ('course_title', models.CharField(max_length=200, null=True)),
                ('lecturers', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_id', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('venue_id', models.CharField(max_length=200, null=True)),
                ('school', models.CharField(max_length=200, null=True)),
                ('day_of_week', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('cohort', models.CharField(max_length=200, null=True)),
                ('course_code', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField(null=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(max_length=200, null=True)),
                ('reg_no', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField(null=True)),
                ('school', models.CharField(max_length=200, null=True)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
    ]
