# Generated by Django 2.2.7 on 2019-11-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrep',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
