# Generated by Django 2.2.7 on 2020-01-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_timetable_timetable_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='venue_id',
        ),
    ]
