# Generated by Django 2.2.7 on 2020-01-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_venue_venue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='timetable_id',
            field=models.IntegerField(null=True),
        ),
    ]
