# Generated by Django 2.2.7 on 2020-01-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_timetable_timetable_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='timetable_id',
        ),
    ]
