# Generated by Django 2.2.7 on 2020-01-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_no',
            field=models.CharField(max_length=254, unique=True, verbose_name='reg_no'),
        ),
    ]
